server:
  port: ${port:8910}
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    instance:
      preferIpAddress: true